### ISSUE TITLE
entrypoint.sh + chmod

### ISSUE THREAD

**Issue by webxI23** [avluis/iroffer#1]
The container won't run. I have this error :

docker: Error response from daemon: OCI runtime create failed: container_linux.go:296: starting container process caused "exec: \"entrypoint.sh\": executable file not found in $PATH": unknown.

-----------------------------------

I think a "chmod +x" is missing on the file /usr/local/bin/entrypoint.sh.

The link seems OK but not the destination file.

root@b56202493474:/# ls entrypoint.sh -al
lrwxrwxrwx. 1 root root 27 Sep  1 16:52 entrypoint.sh -> usr/local/bin/entrypoint.sh

root@b56202493474:/# ls /usr/local/bin/entrypoint.sh  -al
-rw-rw-rw-. 1 root root 777 Aug 31 10:18 /usr/local/bin/entrypoint.sh

**Comment by avluis** [comment]
Hey there.
Looks like GitHub failed to send me a notification when this issue was posted.

In regards to this repo -- I actually maintain my own CI so changes are done there before they make their way here.
My Docker Hub will always contain the latest changes and this repo will have those changes later on once I make sure everything works OK.

---
As for the issue described here -- it has already been addressed and will be making its way to this repo in a bit.
